export const FETCH_MONTH = "FETCH_MONTH";
export const FETCH_YEAR = "FETCH_YEAR";
export const FETCH_DOUGHNUTDATA = "FETCH_DOUGHNUTDATA";
export const FETCH_EXPENSES = "FETCH_EXPENSES";
export const SET_EXPLODEINDEX = "SET_EXPLODEINDEX";
